namespace ChronoPos.Application.DTOs;

/// <summary>
/// Data Transfer Object for Product Sales Information on Dashboard
/// </summary>
public class ProductSalesDto
{
    /// <summary>
    /// Product identifier
    /// </summary>
    public int ProductId { get; set; }

    /// <summary>
    /// Product name
    /// </summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>
    /// Product SKU/Code
    /// </summary>
    public string? Sku { get; set; }

    /// <summary>
    /// Path to product image
    /// </summary>
    public string? ImagePath { get; set; }

    /// <summary>
    /// Number of units sold in the period
    /// </summary>
    public int UnitsSold { get; set; }

    /// <summary>
    /// Total revenue generated by this product
    /// </summary>
    public decimal Revenue { get; set; }

    /// <summary>
    /// Current stock quantity
    /// </summary>
    public int StockQuantity { get; set; }

    /// <summary>
    /// Stock status text (In Stock, Low Stock, Out of Stock)
    /// </summary>
    public string StockStatus { get; set; } = "Unknown";

    /// <summary>
    /// Product color for UI display
    /// </summary>
    public string? Color { get; set; }

    /// <summary>
    /// Category name
    /// </summary>
    public string? CategoryName { get; set; }

    /// <summary>
    /// Unit price
    /// </summary>
    public decimal UnitPrice { get; set; }

    /// <summary>
    /// Percentage contribution to total sales
    /// </summary>
    public decimal SalesPercentage { get; set; }
}
